package com.markleaf.notes.res

import androidx.test.core.app.ApplicationProvider
import com.markleaf.notes.LocaleManifest
import com.markleaf.notes.R
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.xmlpull.v1.XmlPullParser

/**
 * The per-app language list Android 13+ shows under Settings → App languages
 * (#262 `## v2.45.0`).
 *
 * The list is generated by AGP (`androidResources.generateLocaleConfig`) from
 * the `values-<code>` directories, so it cannot drift on its own — but two
 * things can still break it without anything else going red: the flag being
 * dropped (the reference below stops compiling), and a dependency starting to
 * contribute its own locales, which would offer languages Markleaf has no
 * strings for. Held to `config/locales.tsv` in both directions.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class LocaleConfigTest {

    @Test
    fun theLocaleConfigListsExactlyTheShippedLanguages() {
        val resources = ApplicationProvider.getApplicationContext<android.content.Context>().resources
        val listed = mutableListOf<String>()
        resources.getXml(R.xml._generated_res_locale_config).use { parser ->
            while (parser.next() != XmlPullParser.END_DOCUMENT) {
                if (parser.eventType == XmlPullParser.START_TAG && parser.name == "locale") {
                    listed += parser.getAttributeValue(ANDROID_NS, "name")
                }
            }
        }

        // A region tag for the source (from res/resources.properties), bare codes for the rest.
        assertEquals(
            LocaleManifest.entries.map { it.code }.sorted(),
            listed.map { it.substringBefore('-') }.sorted()
        )
        val source = LocaleManifest.source
        assertEquals(
            "res/resources.properties unqualifiedResLocale vs config/locales.tsv",
            source.store,
            listed.first { it.substringBefore('-') == source.code }
        )
    }

    private companion object {
        const val ANDROID_NS = "http://schemas.android.com/apk/res/android"
    }
}
